# Autogenerated wrapper script for SIRIUS_jll for x86_64-linux-gnu-libgfortran5-cxx03-mpi+mpich
export libsirius

using nlcglib_jll
using GSL_jll
using SCALAPACK32_jll
using libblastrampoline_jll
using Libxc_jll
using HDF5_jll
using Doxygen_jll
using spglib_jll
using spla_jll
using SpFFT_jll
using COSTA_jll
using CompilerSupportLibraries_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("SIRIUS")
JLLWrappers.@declare_library_product(libsirius, "libsirius.so")
function __init__()
    JLLWrappers.@generate_init_header(nlcglib_jll, GSL_jll, SCALAPACK32_jll, libblastrampoline_jll, Libxc_jll, HDF5_jll, Doxygen_jll, spglib_jll, spla_jll, SpFFT_jll, COSTA_jll, CompilerSupportLibraries_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libsirius,
        "lib/libsirius.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
