# Autogenerated wrapper script for SIRIUS_jll for x86_64-linux-gnu-libgfortran5-cxx03-mpi+openmpi
export libsirius

using GSL_jll
using pugixml_jll
using libblastrampoline_jll
using Libxc_jll
using HDF5_jll
using spglib_jll
using spla_jll
using SpFFT_jll
using COSTA_jll
using CompilerSupportLibraries_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("SIRIUS")
JLLWrappers.@declare_library_product(libsirius, "libsirius.so")
function __init__()
    JLLWrappers.@generate_init_header(GSL_jll, pugixml_jll, libblastrampoline_jll, Libxc_jll, HDF5_jll, spglib_jll, spla_jll, SpFFT_jll, COSTA_jll, CompilerSupportLibraries_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libsirius,
        "lib/libsirius.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
